// ─────────────────────────────────────────────────────────────────────────────
// Destination Template Data
// Rich, curated data for popular destinations used in mock/dev mode.
// ─────────────────────────────────────────────────────────────────────────────

import type { DestinationTemplate } from './generator';

export const DESTINATION_DATA: Record<string, DestinationTemplate> = {
  paris: {
    name: 'Paris',
    airportCode: 'CDG',
    currency: 'EUR',
    climate: 'temperate',
    highlights: [
      'Eiffel Tower at sunset',
      'Louvre Museum',
      'Montmartre & Sacré-Cœur',
      'Seine River cruise',
      'Versailles day trip',
    ],
    ariaRecommendation: 'Paris is perfect for couples and culture lovers. I\'d allocate 2 nights in Le Marais for walkability, and 2 in Saint-Germain-des-Prés for the café culture.',
    safetyTips: [
      'Be vigilant around tourist landmarks for pickpockets.',
      'The Métro is safe but watch your belongings during peak hours.',
      'Emergency: 112 (EU), 17 (Police), 15 (Medical)',
    ],
    usefulApps: ['RATP (metro)', 'Google Maps', 'The Fork (restaurants)', 'Citymapper'],
    packingList: [
      'Comfortable walking shoes', 'Light layers for evenings',
      'Compact umbrella', 'Portable charger', 'Museum pass',
      'Euros cash for markets',
    ],
    dayTemplates: [
      {
        theme: 'Icons of Paris',
        morning: [
          {
            name: 'Eiffel Tower',
            description: 'Start your Paris adventure at the iconic iron lady. Book the summit for panoramic views over the city.',
            type: 'sightseeing',
            duration: '2 hours',
            cost: 29,
            currency: 'EUR',
            address: 'Champ de Mars, 5 Av. Anatole France, 75007 Paris',
            openingHours: '09:00 – 23:45',
            bookingRequired: true,
            rating: 4.7,
            walkMinutes: 15,
            nearbyAttractions: ['Champ de Mars picnic lawn', 'Pont d\'Iéna'],
            indoorAlternative: 'Musée du quai Branly – Jacques Chirac (5 min walk)',
          },
        ],
        afternoon: [
          {
            name: 'Louvre Museum',
            description: 'Home to the Mona Lisa and Venus de Milo. Focus on one wing — the whole museum takes days.',
            type: 'museum',
            duration: '3 hours',
            cost: 22,
            currency: 'EUR',
            address: 'Rue de Rivoli, 75001 Paris',
            openingHours: '09:00 – 18:00 (closed Tue)',
            bookingRequired: true,
            rating: 4.8,
            walkMinutes: 20,
            indoorAlternative: 'Perfect indoor option on rainy days',
          },
          {
            name: 'Tuileries Garden Stroll',
            description: 'Walk through the beautiful formal garden between the Louvre and Place de la Concorde.',
            type: 'sightseeing',
            duration: '45 min',
            walkMinutes: 10,
          },
        ],
        evening: [
          {
            name: 'Seine River Cruise',
            description: 'A sunset cruise past Notre-Dame, the bridges, and illuminated monuments — magical.',
            type: 'local_experience',
            duration: '1.5 hours',
            cost: 18,
            currency: 'EUR',
            bookingRequired: false,
            rating: 4.6,
            walkMinutes: 5,
          },
        ],
        meals: [
          {
            id: 'paris-d1-breakfast',
            mealType: 'breakfast',
            name: 'Café de Flore',
            cuisine: 'French',
            description: 'A legendary Left Bank café where Sartre used to write. Excellent croissants and café au lait.',
            priceRange: '$$',
            address: '172 Bd Saint-Germain, 75006 Paris',
            rating: 4.5,
            mustTryDish: 'Croissant au beurre + café crème',
          },
          {
            id: 'paris-d1-lunch',
            mealType: 'lunch',
            name: 'Ladurée on Champs-Élysées',
            cuisine: 'French Patisserie',
            description: 'Famous for its macarons. Perfect for a light lunch and unforgettable desserts.',
            priceRange: '$$$',
            rating: 4.6,
            mustTryDish: 'Signature macaron box + croque-monsieur',
          },
          {
            id: 'paris-d1-dinner',
            mealType: 'dinner',
            name: 'Le Comptoir du Relais',
            cuisine: 'French Bistro',
            description: 'Quintessential Parisian bistro in Saint-Germain. Book well in advance for dinner.',
            priceRange: '$$$',
            address: '9 Carrefour de l\'Odéon, 75006 Paris',
            rating: 4.7,
            reservationRequired: true,
            mustTryDish: 'Foie gras, duck confit',
          },
        ],
        transport: [
          { type: 'metro', description: 'Use Métro Line 6 from Bir-Hakeim to Trocadéro for the Eiffel Tower', duration: '10 min', cost: '€1.90' },
          { type: 'walk', description: 'Louvre to Tuileries is a pleasant 15-min walk along the Seine', duration: '15 min', tip: 'Buy a Navigo carnet (10-trip pass) for value' },
        ],
        hiddenGems: [
          'Rue Crémieux — pastel-coloured houses, amazing photos (go early to avoid crowds)',
          'Marché d\'Aligre — authentic local market, far from tourist prices',
        ],
        photoSpots: [
          'Trocadéro Gardens — symmetrical Eiffel Tower view',
          'Pont de Bir-Hakeim — cinematic bridge shots',
        ],
        insiderTips: [
          'Visit the Louvre on Wednesday or Friday evening — open until 21:45 and much less crowded.',
          'The Eiffel Tower glitters for 5 minutes every hour after dark — spectacular for photos.',
        ],
      },
      {
        theme: 'Montmartre & Le Marais',
        morning: [
          {
            name: 'Montmartre Village Walk',
            description: 'Explore the bohemian hilltop district beloved by Picasso and Van Gogh. Wind through cobblestone streets and artist studios.',
            type: 'sightseeing',
            duration: '2 hours',
            walkMinutes: 30,
            rating: 4.8,
            nearbyAttractions: ['Place du Tertre', 'Moulin Rouge (exterior)'],
          },
          {
            name: 'Sacré-Cœur Basilica',
            description: 'The stunning white basilica atop Montmartre with the best 360° view of Paris — and it\'s free.',
            type: 'culture',
            duration: '45 min',
            cost: 0,
            address: '35 Rue du Chevalier de la Barre, 75018 Paris',
            openingHours: '06:00 – 22:30',
            rating: 4.8,
          },
        ],
        afternoon: [
          {
            name: 'Le Marais District',
            description: 'Paris\'s most fashionable neighbourhood. Home to the Jewish Quarter, boutiques, galleries, and the Picasso Museum.',
            type: 'culture',
            duration: '3 hours',
            walkMinutes: 25,
          },
          {
            name: 'Place des Vosges',
            description: 'Paris\'s oldest planned square — arcaded red-brick elegance. Victor Hugo lived here.',
            type: 'sightseeing',
            duration: '30 min',
            cost: 0,
            rating: 4.7,
          },
        ],
        evening: [
          {
            name: 'Pigalle / SoPi Neighbourhood',
            description: 'The reinvented Pigalle is now Paris\'s hippest neighbourhood — natural wine bars, cocktail lounges, and live music.',
            type: 'entertainment',
            duration: '3 hours',
          },
        ],
        meals: [
          {
            id: 'paris-d2-breakfast',
            mealType: 'breakfast',
            name: 'La Maison Rose',
            cuisine: 'French',
            description: 'The iconic pink house café in Montmartre. Instagram-perfect and delicious.',
            priceRange: '$$',
            rating: 4.4,
            mustTryDish: 'Pain perdu, fresh orange juice',
          },
          {
            id: 'paris-d2-lunch',
            mealType: 'lunch',
            name: 'L\'As du Fallafel',
            cuisine: 'Jewish-Israeli',
            description: 'A Paris institution in the Jewish Quarter. The best falafel you\'ll ever eat.',
            priceRange: '$',
            address: '34 Rue des Rosiers, 75004',
            rating: 4.7,
            mustTryDish: 'Special falafel sandwich with eggplant',
          },
          {
            id: 'paris-d2-dinner',
            mealType: 'dinner',
            name: 'Septime',
            cuisine: 'Modern French',
            description: 'One of Paris\'s best restaurants. Creative, seasonal tasting menu in a relaxed industrial space.',
            priceRange: '$$$$',
            reservationRequired: true,
            rating: 4.9,
            mustTryDish: 'Chef\'s seasonal tasting menu',
          },
        ],
        transport: [
          { type: 'metro', description: 'Line 2 to Anvers for Montmartre, then Line 8 to Chemin Vert for Le Marais', duration: '25 min' },
          { type: 'walk', description: 'Most of Le Marais is best explored on foot — wear comfortable shoes', tip: 'The neighbourhood closes many shops on Saturday afternoons' },
        ],
        hiddenGems: [
          'Passage des Abbesses — a tiny secret alley with a mosaic fountain',
          'Marché des Enfants Rouges — Paris\'s oldest covered market, hidden behind an archway',
        ],
        photoSpots: [
          'Rue de l\'Abreuvoir — the most photographed street in Montmartre',
          'Cour Damoye — a secret cobblestone passage near Bastille',
        ],
        insiderTips: [
          'Take the funicular up to Sacré-Cœur instead of the stairs — same Métro ticket, saves energy.',
          'Le Marais is best explored on Sunday when the Jewish Quarter is at its liveliest.',
        ],
      },
    ],
  },

  tokyo: {
    name: 'Tokyo',
    airportCode: 'NRT',
    currency: 'JPY',
    climate: 'temperate',
    highlights: [
      'Shibuya Crossing',
      'Senso-ji Temple',
      'TeamLab Planets',
      'Tsukiji Outer Market',
      'Harajuku & Takeshita Street',
    ],
    ariaRecommendation: 'Tokyo is endlessly fascinating. I recommend splitting your stay between Shinjuku (great nightlife and convenience) and Asakusa (historic temples and traditional culture).',
    safetyTips: [
      'Tokyo is one of the world\'s safest cities.',
      'Emergency: 110 (Police), 119 (Fire/Ambulance)',
      'Always carry your passport — it\'s required for ID.',
    ],
    usefulApps: ['Suica (transit card)', 'Google Translate (camera mode)', 'HyperDia (rail)', 'Google Maps'],
    packingList: [
      'Comfortable walking shoes (remove at temples)',
      'Pocket WiFi or SIM card',
      'Cash (many places still cash-only)',
      'Portable umbrella',
      'Small backpack for day trips',
    ],
    dayTemplates: [
      {
        theme: 'Modern Tokyo — Shibuya & Harajuku',
        morning: [
          {
            name: 'Meiji Jingu Shrine',
            description: 'Peaceful forest shrine in the heart of the city. A serene morning walk through towering torii gates and ancient cedars.',
            type: 'culture',
            duration: '1.5 hours',
            cost: 0,
            address: '1-1 Yoyogikamizonocho, Shibuya, Tokyo',
            openingHours: 'Sunrise to sunset',
            rating: 4.8,
            walkMinutes: 20,
          },
          {
            name: 'Harajuku & Takeshita Street',
            description: 'The epicentre of Japan\'s wild youth fashion. Crepe shops, vintage stores, and outrageous street style.',
            type: 'shopping',
            duration: '1 hour',
            rating: 4.5,
            walkMinutes: 10,
          },
        ],
        afternoon: [
          {
            name: 'Shibuya Crossing & Sky',
            description: 'Watch the world\'s busiest pedestrian crossing from above at Shibuya Sky observation deck.',
            type: 'sightseeing',
            duration: '2 hours',
            cost: 2000,
            currency: 'JPY',
            bookingRequired: true,
            rating: 4.9,
          },
          {
            name: 'Shibuya 109 & Shopping',
            description: 'Tokyo\'s iconic fashion department store surrounded by boutiques, cafés, and pop-up stores.',
            type: 'shopping',
            duration: '1.5 hours',
          },
        ],
        evening: [
          {
            name: 'Shinjuku Golden Gai',
            description: 'A labyrinth of over 200 tiny bars each seating 5-8 people. One of Tokyo\'s most unique nightlife experiences.',
            type: 'entertainment',
            duration: '3 hours',
            rating: 4.8,
          },
        ],
        meals: [
          {
            id: 'tokyo-d1-breakfast',
            mealType: 'breakfast',
            name: 'Ichiran Ramen',
            cuisine: 'Japanese Ramen',
            description: 'Solo ramen booths where you order via ticket machine. The ultimate Tokyo breakfast ritual.',
            priceRange: '$',
            rating: 4.7,
            mustTryDish: 'Original tonkotsu ramen with extra flavour',
          },
          {
            id: 'tokyo-d1-lunch',
            mealType: 'lunch',
            name: 'Tsukiji Outer Market',
            cuisine: 'Japanese Seafood',
            description: 'Fresh sushi, tamagoyaki, and seafood skewers at the world\'s most famous fish market.',
            priceRange: '$$',
            rating: 4.8,
            mustTryDish: 'Freshest tuna sushi you\'ll ever eat',
          },
          {
            id: 'tokyo-d1-dinner',
            mealType: 'dinner',
            name: 'Sukiyabashi Jiro Honten',
            cuisine: 'Omakase Sushi',
            description: 'The legendary 3-Michelin-star sushi counter made famous by Jiro Dreams of Sushi.',
            priceRange: '$$$$',
            reservationRequired: true,
            rating: 5.0,
            mustTryDish: 'Chef\'s omakase (30,000¥+)',
          },
        ],
        transport: [
          { type: 'metro', description: 'JR Yamanote Line connects all major neighbourhoods efficiently', duration: '10-20 min', cost: '¥150-250', tip: 'Buy a Suica card — tap in/out everywhere' },
        ],
        hiddenGems: [
          'Yanaka — a preserved old Tokyo neighbourhood that survived WWII bombing',
          'Nonbei Yokocho — "Whisky Alley" in Shibuya, hidden behind the station',
        ],
        photoSpots: [
          'Shibuya Sky at sunset — golden hour over the crossing',
          'Shinjuku at night — neon reflections in the rain',
        ],
        insiderTips: [
          'Get a 7-day JR Pass before arriving — saves significant money on bullet trains.',
          'Convenience stores (7-Eleven, FamilyMart) serve genuinely excellent food — don\'t skip them.',
        ],
      },
    ],
  },

  bali: {
    name: 'Bali',
    airportCode: 'DPS',
    currency: 'IDR',
    climate: 'tropical',
    highlights: [
      'Ubud Sacred Monkey Forest',
      'Tegalalang Rice Terraces',
      'Tanah Lot Temple at sunset',
      'Seminyak Beach',
      'Mount Batur sunrise hike',
    ],
    ariaRecommendation: 'Bali offers an incredible mix of spirituality, nature, and beach life. I recommend splitting your time: 2 nights in Ubud (culture & nature), 2 nights in Seminyak (beach & nightlife), and 1 night in Uluwatu (dramatic cliffs & Kecak fire dance).',
    safetyTips: [
      'Drink bottled water only.',
      'Negotiate prices at markets before buying.',
      'Dress modestly when visiting temples (sarong required).',
      'Emergency: 110 (Police), 118 (Ambulance)',
    ],
    usefulApps: ['Gojek (rides & food)', 'Google Maps', 'XE Currency'],
    packingList: [
      'Sarong (temple entry)',
      'Reef-safe sunscreen',
      'Mosquito repellent',
      'Light breathable clothing',
      'Cash (IDR) for local markets',
      'Waterproof bag for rice terrace walks',
    ],
    dayTemplates: [
      {
        theme: 'Ubud — Culture, Temples & Rice Terraces',
        morning: [
          {
            name: 'Tegalalang Rice Terraces',
            description: 'UNESCO-protected cascading rice terraces. Arrive early (7am) to avoid the crowds and get the best light.',
            type: 'nature',
            duration: '2 hours',
            cost: 15000,
            currency: 'IDR',
            address: 'Tegalalang, Gianyar Regency',
            openingHours: '07:00 – 18:00',
            rating: 4.7,
            walkMinutes: 45,
            indoorAlternative: 'ARMA Museum (Agung Rai Museum of Art)',
          },
        ],
        afternoon: [
          {
            name: 'Ubud Sacred Monkey Forest Sanctuary',
            description: 'Ancient temple complex and natural reserve home to 1,260 Balinese macaques. Surreal and magical.',
            type: 'nature',
            duration: '2 hours',
            cost: 80000,
            currency: 'IDR',
            bookingRequired: false,
            rating: 4.6,
            walkMinutes: 20,
          },
          {
            name: 'Ubud Art Market',
            description: 'Two-storey traditional market selling batik, wooden carvings, sarongs, and silver jewellery. Bargaining expected.',
            type: 'shopping',
            duration: '1 hour',
            rating: 4.3,
          },
        ],
        evening: [
          {
            name: 'Kecak Fire Dance at Pura Uluwatu',
            description: 'Dramatic traditional Balinese fire dance performed at sunset on the cliff edge of Uluwatu Temple. Unforgettable.',
            type: 'culture',
            duration: '2 hours',
            cost: 100000,
            currency: 'IDR',
            bookingRequired: true,
            rating: 4.9,
          },
        ],
        meals: [
          {
            id: 'bali-d1-breakfast',
            mealType: 'breakfast',
            name: 'Locavore NXT',
            cuisine: 'Modern Balinese',
            description: 'Zero-waste concept restaurant. Use local ingredients creatively — one of Asia\'s best.',
            priceRange: '$$$',
            rating: 4.9,
            mustTryDish: 'Smoked banana blossom with coconut sambal',
          },
          {
            id: 'bali-d1-lunch',
            mealType: 'lunch',
            name: 'Warung Babi Guling Ibu Oka',
            cuisine: 'Balinese',
            description: 'Famous suckling pig warung made famous by Anthony Bourdain. Cash only, queue early.',
            priceRange: '$',
            rating: 4.6,
            mustTryDish: 'Babi guling (suckling pig) with rice',
          },
          {
            id: 'bali-d1-dinner',
            mealType: 'dinner',
            name: 'Bridges Bali',
            cuisine: 'International',
            description: 'Romantic restaurant over the Campuhan gorge. Perfect for couples.',
            priceRange: '$$$',
            reservationRequired: true,
            rating: 4.7,
            mustTryDish: 'Grilled barramundi with sambal matah',
          },
        ],
        transport: [
          { type: 'uber', description: 'Use Gojek (local ride-hailing) — much cheaper than taxis', cost: '~IDR 30,000 for most Ubud trips', tip: 'Agree on price before getting in unmetered taxis' },
        ],
        hiddenGems: [
          'Campuhan Ridge Walk — a peaceful 2km walk through jungle and rice paddies (free)',
          'Gunung Kawi — ancient carved rock temples, far fewer tourists than Tanah Lot',
        ],
        photoSpots: [
          'Tegalalang at 7am with morning mist rising from the terraces',
          'Handara Gate — iconic Bali split gate surrounded by misty mountains',
        ],
        insiderTips: [
          'IDR 500,000 (~$32) can cover a full day of food, activities, and transport in Ubud.',
          'Hire a driver for the day (~$40-50) — cheaper than Gojek for multiple stops and they know the temples.',
        ],
      },
    ],
  },
};

// Alias keys for common query variations
DESTINATION_DATA['tokyo, japan'] = DESTINATION_DATA['tokyo'];
DESTINATION_DATA['paris, france'] = DESTINATION_DATA['paris'];
DESTINATION_DATA['bali, indonesia'] = DESTINATION_DATA['bali'];
DESTINATION_DATA['ubud'] = DESTINATION_DATA['bali'];
DESTINATION_DATA['seminyak'] = DESTINATION_DATA['bali'];
